name: Sonar Location Rider

on:
  workflow_run:
    workflows: ["Build Location Rider"]
    types: [completed]

jobs:
  sonar:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: hendafarhani/github-actions-workflows/.github/workflows/sonar.yml@main
    with:
      java_version: "21"
      sonar_project_key: "hendafarhani_location-rider"
      sonar_organization: "hendafarhani"
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
